version: "3"
services:
    web:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux:ctp1-3"
        volumes: 
            - "/home/vin/aqvolume:/var/opt/mssql"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Luis9000"
            ACCEPT_EULA: "Y"
